---
title: "Other data variable analysis"
author: "Girish Tillu, Ashwini Mathur, Vinay Mahajan"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  word_document:
    toc: yes
    toc_depth: '3'
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(data.table)
library(ggplot2)
library(dplyr)
library(anytime)
library(knitr)
library(DT)

#Read each dataset:
#user@DESKTOP-13IUJT2 /cygdrive/d/Hospital_data/ProgresSQL/analysis
#$ ls -1 *rds|tr "." " "|awk '{print $1, "<- readRDS(\"D:/Hospital_data/ProgresSQL/analysis/" $1 ".rds\")"}'

sec001 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec001.rds")
sec002 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec002.rds")
sec003 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec003.rds")
sec004 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec004.rds")
sec006 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec006.rds")
sec007 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec007.rds")
sec008 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec008.rds")
sec009 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec009.rds")
sec010 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec010.rds")
sec011 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec011.rds")
sec012 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec012.rds")
sec013 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec013.rds")
sec014 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec014.rds")
sec017 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec017.rds")
sec019 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec019.rds")
sec020 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec020.rds")
sec021 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec021.rds")
sec022 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec022.rds")
sec023 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec023.rds")
sec024 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec024.rds")
sec026 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec026.rds")
sec027 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec027.rds")
sec030 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec030.rds")
sec031 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec031.rds")
sec032 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec032.rds")
sec033 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec033.rds")
sec034 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec034.rds")
sec035 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec035.rds")
sec036 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec036.rds")
sec037 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec037.rds")
sec038 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec038.rds")
sec044 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec044.rds")
sec077 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec077.rds")
sec078 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec078.rds")
sec079 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec079.rds")
sec080 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec080.rds")
sec081 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec081.rds")
sec082 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec082.rds")
sec083 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec083.rds")
sec084 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec084.rds")
sec085 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec085.rds")
sec086 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec086.rds")
sec088 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec088.rds")
sec089 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec089.rds")
sec099 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec099.rds")
sec100 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec100.rds")
sec101 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec101.rds")
sec102 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec102.rds")
sec103 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec103.rds")
sec106 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec106.rds")
sec111 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec111.rds")
sec112 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec112.rds")
sec114 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec114.rds")
sec115 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec115.rds")
sec116 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec116.rds")
sec119 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec119.rds")
sec120 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec120.rds")
sec122 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec122.rds")
sec123 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec123.rds")
sec124 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec124.rds")
sec126 <- readRDS("D:/Hospital_data/ProgresSQL/analysis/sec126.rds")
secNA <- readRDS("D:/Hospital_data/ProgresSQL/analysis/secNA.rds")

```

```{r, echo=FALSE}
#####################################################
#Create a macro call for the dplyr distinct function
#####################################################

#user@DESKTOP-13IUJT2 /cygdrive/d/Hospital_data/ProgresSQL/analysis
#$ ls -1 sec*csv|grep -v "_"|gawk '{print "cat", $1, "|head -n 1"}' |sh|tr "," "\n"|grep "sec"|awk -F"_" '{print "(distinct(" $1 ",`" $0 "`))"}'

(distinct(sec001,`sec001_var001_Location`))
(distinct(sec001,`sec001_var002_Quality`))
(distinct(sec001,`sec001_var003_Duration`))
(distinct(sec001,`sec001_var004_Context`))
(distinct(sec001,`sec001_var005_Modifying Factors`))
(distinct(sec001,`sec001_var006_Associated Signs & Symptoms`))
(distinct(sec001,`sec001_var007_Additional Complaint`))
(distinct(sec001,`sec001_var008_Diabetes`))
(distinct(sec001,`sec001_var009_Hypertension`))
(distinct(sec001,`sec001_var010_Allergy`))
(distinct(sec001,`sec001_var011_Renal Diseases`))
(distinct(sec001,`sec001_var012_Liver Diseases`))
(distinct(sec001,`sec001_var013_Food Allergy`))
(distinct(sec001,`sec001_var014_Food Intolerance`))
#(distinct(sec001,`sec001_var015_Chief Complaint with Onset & Duration`))
(distinct(sec001,`sec001_var016_Upashaya`))
(distinct(sec001,`sec001_var017_Anupashaya`))
#(distinct(sec001,`sec001_var018_Associated Complaint with Onset & Duration`))
(distinct(sec002,`sec002_var001_ENT`))
(distinct(sec002,`sec002_var002_Respiratory`))
(distinct(sec002,`sec002_var003_Abdominal Pain`))
(distinct(sec002,`sec002_var004_Gastrointestinal`))
(distinct(sec002,`sec002_var005_Urinary Frequency`))
(distinct(sec002,`sec002_var006_Joint Pain`))
(distinct(sec002,`sec002_var007_Joint Swelling`))
(distinct(sec002,`sec002_var008_Muscle Pain`))
(distinct(sec002,`sec002_var009_Musculoskeletal`))
(distinct(sec002,`sec002_var010_Integumentary`))
(distinct(sec002,`sec002_var011_Tremor`))
(distinct(sec002,`sec002_var012_Neurological`))
(distinct(sec002,`sec002_var013_Psychiatric`))
(distinct(sec003,`sec003_var001_Eyes`))
(distinct(sec003,`sec003_var002_Sinusitis`))
(distinct(sec003,`sec003_var003_ENT`))
(distinct(sec003,`sec003_var004_Respiratory`))
(distinct(sec003,`sec003_var005_Abdominal Pain`))
(distinct(sec003,`sec003_var006_Gastrointestinal`))
(distinct(sec003,`sec003_var007_Arthralgia`))
(distinct(sec003,`sec003_var008_Edema`))
(distinct(sec003,`sec003_var009_Lumbago`))
(distinct(sec003,`sec003_var010_Myalgia`))
(distinct(sec003,`sec003_var011_Pain in the Limb`))
(distinct(sec003,`sec003_var012_Stiffness`))
(distinct(sec003,`sec003_var013_Swelling`))
(distinct(sec003,`sec003_var014_Musculoskeletal`))
(distinct(sec003,`sec003_var015_Integumentary`))
(distinct(sec003,`sec003_var016_Tremor`))
(distinct(sec003,`sec003_var017_Neurological`))
(distinct(sec003,`sec003_var018_Psychiatric`))
(distinct(sec004,`sec004_var001_Medical History`))
(distinct(sec004,`sec004_var002_Family History`))
(distinct(sec004,`sec004_var003_Diagnostic History`))
(distinct(sec004,`sec004_var004_Surgical History`))
(distinct(sec004,`sec004_var005_Psychological & Occupational History`))
(distinct(sec004,`sec004_var006_Ahara`))
(distinct(sec004,`sec004_var007_Vihara`))
(distinct(sec004,`sec004_var008_Nidra`))
(distinct(sec004,`sec004_var009_Vyayama`))
(distinct(sec004,`sec004_var010_Vyavaya`))
(distinct(sec004,`sec004_var011_Mala`))
(distinct(sec004,`sec004_var012_Mutra`))
(distinct(sec004,`sec004_var013_Madakari Dravya Abhyasa`))
(distinct(sec004,`sec004_var014_Immunization History`))
(distinct(sec004,`sec004_var015_Birth History`))
(distinct(sec004,`sec004_var016_Growth and development History`))
(distinct(sec006,`sec006_var001_Menarche (yrs)`))
(distinct(sec006,`sec006_var002_Menopause (yrs)`))
(distinct(sec006,`sec006_var003_MH`))
(distinct(sec006,`sec006_var004_LMP`))
(distinct(sec006,`sec006_var005_PMH`))
(distinct(sec006,`sec006_var006_Colour`))
(distinct(sec006,`sec006_var007_Consistency`))
(distinct(sec006,`sec006_var008_Characteristics`))
(distinct(sec006,`sec006_var009_Flow`))
(distinct(sec006,`sec006_var010_Clots`))
(distinct(sec006,`sec006_var011_Smell`))
(distinct(sec006,`sec006_var012_Discharge`))
(distinct(sec006,`sec006_var013_Pre Menstrual Symptoms`))
(distinct(sec006,`sec006_var014_Menopausal Symptoms`))
(distinct(sec007,`sec007_var001_Married`))
(distinct(sec007,`sec007_var002_Single`))
(distinct(sec007,`sec007_var003_Widow`))
(distinct(sec007,`sec007_var004_FTND`))
(distinct(sec007,`sec007_var005_Mode of Delivery`))
(distinct(sec007,`sec007_var006_PTND`))
(distinct(sec007,`sec007_var007_LSCS`))
(distinct(sec007,`sec007_var008_Instrumental`))
(distinct(sec007,`sec007_var009_Complications`))
(distinct(sec007,`sec007_var010_LMP`))
(distinct(sec007,`sec007_var011_POG`))
(distinct(sec007,`sec007_var012_EDD`))
(distinct(sec007,`sec007_var013_OH`))
(distinct(sec007,`sec007_var014_G`))
(distinct(sec007,`sec007_var015_P`))
(distinct(sec007,`sec007_var016_A`))
(distinct(sec007,`sec007_var017_L`))
(distinct(sec007,`sec007_var018_D`))
(distinct(sec007,`sec007_var019_Antenatal/Foetal History`))
(distinct(sec008,`sec008_var001_Rasa`))
(distinct(sec008,`sec008_var002_Dooshya`))
(distinct(sec008,`sec008_var003_Rakta`))
(distinct(sec008,`sec008_var004_Mamsa`))
(distinct(sec008,`sec008_var005_Asthi`))
(distinct(sec008,`sec008_var006_Majja`))
(distinct(sec008,`sec008_var007_Mala`))
(distinct(sec008,`sec008_var008_Mutra`))
(distinct(sec008,`sec008_var009_Stanya`))
(distinct(sec008,`sec008_var010_Artava`))
(distinct(sec008,`sec008_var011_Sira`))
(distinct(sec008,`sec008_var012_Twacha`))
(distinct(sec008,`sec008_var013_Snayu`))
(distinct(sec008,`sec008_var014_Srotas`))
(distinct(sec008,`sec008_var015_Raktavaha`))
(distinct(sec008,`sec008_var016_Mamsavaha`))
(distinct(sec008,`sec008_var017_Asthivaha`))
(distinct(sec008,`sec008_var018_Majjavaha`))
(distinct(sec008,`sec008_var019_Mutravaha`))
(distinct(sec008,`sec008_var020_Manovaha`))
(distinct(sec008,`sec008_var021_Ati pravrutti`))
(distinct(sec008,`sec008_var022_Sangha`))
(distinct(sec008,`sec008_var023_Vimarga gamana`))
(distinct(sec008,`sec008_var024_Sira granthi`))
(distinct(sec009,`sec009_var001_Nidana....`))
(distinct(sec009,`sec009_var002_Poorvaroopa`))
(distinct(sec009,`sec009_var003_Roopa`))
(distinct(sec009,`sec009_var004_Ahara`))
(distinct(sec009,`sec009_var005_Vihara`))
(distinct(sec009,`sec009_var006_Vyasana`))
(distinct(sec009,`sec009_var007_Manasika`))
(distinct(sec009,`sec009_var008_Abhighata`))
(distinct(sec010,`sec010_var001_Session Start Time`))
(distinct(sec010,`sec010_var002_Session End Time`))
(distinct(sec010,`sec010_var003_Screening Doctor`))
(distinct(sec011,`sec011_var001_Allopathic Diagnosis`))
(distinct(sec012,`sec012_var001_Examination`))
(distinct(sec012,`sec012_var002_Neurological`))
(distinct(sec012,`sec012_var003_Ophthalmic`))
(distinct(sec012,`sec012_var004_ENT`))
(distinct(sec012,`sec012_var005_Cardiovascular`))
(distinct(sec012,`sec012_var006_Respiratory`))
(distinct(sec012,`sec012_var007_Gastrointestinal`))
(distinct(sec012,`sec012_var008_Urinary`))
(distinct(sec012,`sec012_var009_Genital`))
(distinct(sec012,`sec012_var010_Musculoskeletal`))
(distinct(sec012,`sec012_var011_Integumentary`))
(distinct(sec012,`sec012_var012_Endocrine`))
(distinct(sec012,`sec012_var013_Psychiatric`))
(distinct(sec012,`sec012_var014_Hemotological/Lymphatic`))
(distinct(sec012,`sec012_var015_Allergic/Immunologic`))
(distinct(sec012,`sec012_var016_Local Examination`))
(distinct(sec012,`sec012_var017_All other systems`))
(distinct(sec013,`sec013_var001_Investigation Reports`))
(distinct(sec014,`sec014_var001_Complaint`))
#(distinct(sec014,`sec014_var002_Doctor's Notes`))
(distinct(sec014,`sec014_var003_Source of History`))
(distinct(sec017,`sec017_var001_Examinationm`))
(distinct(sec017,`sec017_var002_VAS`))
(distinct(sec017,`sec017_var003_Tenderness`))
(distinct(sec017,`sec017_var004_Crepitation's`))
(distinct(sec017,`sec017_var005_Measurement of the knee`))
(distinct(sec017,`sec017_var006_Goniometric assessment`))
(distinct(sec017,`sec017_var007_Examination`))
(distinct(sec019,`sec019_var001_Rasa`))
(distinct(sec019,`sec019_var002_Rakta`))
(distinct(sec019,`sec019_var003_Mamsa`))
(distinct(sec019,`sec019_var004_Meda`))
(distinct(sec019,`sec019_var005_Asthi`))
(distinct(sec019,`sec019_var006_Majja`))
(distinct(sec019,`sec019_var007_Shukra`))
(distinct(sec019,`sec019_var008_Satva`))
(distinct(sec020,`sec020_var001_Normal`))
(distinct(sec020,`sec020_var002_Poor`))
(distinct(sec020,`sec020_var003_Yes`))
(distinct(sec020,`sec020_var004_No`))
(distinct(sec020,`sec020_var005_Yes`))
(distinct(sec020,`sec020_var006_No`))
(distinct(sec020,`sec020_var007_Junk Foods`))
(distinct(sec020,`sec020_var008_Untimely Food`))
(distinct(sec020,`sec020_var009_Excessive Food`))
(distinct(sec020,`sec020_var010_Yes`))
(distinct(sec020,`sec020_var011_No`))
(distinct(sec020,`sec020_var012_Yes`))
(distinct(sec020,`sec020_var013_No`))
(distinct(sec020,`sec020_var014_Yes`))
(distinct(sec020,`sec020_var015_No`))
(distinct(sec020,`sec020_var016_Yes`))
(distinct(sec020,`sec020_var017_No`))
(distinct(sec020,`sec020_var018_Consultant Dietic Restrictions`))
(distinct(sec020,`sec020_var019_General Dietic restrictions`))
(distinct(sec021,`sec021_var001_Appearance`))
(distinct(sec021,`sec021_var002_Body Built`))
(distinct(sec021,`sec021_var003_Body Strength`))
(distinct(sec021,`sec021_var004_Orientation`))
(distinct(sec021,`sec021_var005_Conciousness`))
(distinct(sec021,`sec021_var006_Appearance`))
(distinct(sec021,`sec021_var007_Pallor`))
(distinct(sec021,`sec021_var008_Jaundice`))
(distinct(sec021,`sec021_var009_Odema`))
(distinct(sec021,`sec021_var010_Lymphadenopathy`))
(distinct(sec021,`sec021_var011_Nourishment`))
(distinct(sec021,`sec021_var012_Posture`))
(distinct(sec021,`sec021_var013_Mental State`))
(distinct(sec021,`sec021_var014_Facies`))
(distinct(sec022,`sec022_var001_Shashankasana breathing`))
(distinct(sec022,`sec022_var002_Side leg raising`))
(distinct(sec022,`sec022_var003_Straight leg raising`))
(distinct(sec022,`sec022_var004_Naukasana breathing`))
(distinct(sec023,`sec023_var005_Shoulder rotation`))
(distinct(sec023,`sec023_var006_Elbow movements/Rotation`))
(distinct(sec023,`sec023_var007_Wrist movements/rotation`))
(distinct(sec023,`sec023_var008_Finger joint loosening`))
(distinct(sec023,`sec023_var009_Waist rotation`))
(distinct(sec023,`sec023_var010_Forward/backward bending`))
(distinct(sec023,`sec023_var011_Side bending`))
(distinct(sec023,`sec023_var012_Twisting`))
(distinct(sec023,`sec023_var013_Alternate toe touching`))
(distinct(sec023,`sec023_var014_Drill walking`))
(distinct(sec023,`sec023_var015_Knee bending`))
(distinct(sec023,`sec023_var016_Ankle movement/rotation`))
(distinct(sec023,`sec023_var017_Toe bending`))
(distinct(sec023,`sec023_var018_Sit-ups`))
(distinct(sec024,`sec024_var001_Utkatasana`))
(distinct(sec024,`sec024_var002_Ardhakati-chakrasana`))
(distinct(sec024,`sec024_var003_Ardha-chakrasana`))
(distinct(sec024,`sec024_var004_Vrikshasana`))
(distinct(sec024,`sec024_var005_Tadasana`))
(distinct(sec024,`sec024_var006_Vajrasana`))
(distinct(sec024,`sec024_var007_Paschimottanasana`))
(distinct(sec024,`sec024_var008_Padmasana`))
(distinct(sec024,`sec024_var009_Yogamudrsana`))
(distinct(sec024,`sec024_var010_Vakrasana`))
(distinct(sec024,`sec024_var011_Shashankasana`))
(distinct(sec024,`sec024_var012_Bhujangasana`))
(distinct(sec024,`sec024_var013_Shalabhasana`))
(distinct(sec024,`sec024_var014_Naukasana`))
(distinct(sec024,`sec024_var015_Shavasana`))
(distinct(sec026,`sec026_var001_Yogic breathing`))
(distinct(sec026,`sec026_var002_Suryaanuloma`))
(distinct(sec026,`sec026_var003_Nadishodhana`))
(distinct(sec026,`sec026_var004_Bhramari`))
(distinct(sec026,`sec026_var005_Sadanta`))
(distinct(sec026,`sec026_var006_Sheetali`))
(distinct(sec026,`sec026_var007_Sheetkari`))
(distinct(sec027,`sec027_var001_Jnana mudra`))
(distinct(sec030,`sec030_var001_Nadanusandhana`))
(distinct(sec031,`sec031_var001_Chief Complaint & Duration`))
(distinct(sec031,`sec031_var002_History Of Present Illness`))
(distinct(sec031,`sec031_var003_Surgical History`))
(distinct(sec031,`sec031_var004_Bowel`))
(distinct(sec031,`sec031_var005_Appetite`))
(distinct(sec031,`sec031_var006_Micturation`))
(distinct(sec031,`sec031_var007_Sleep`))
(distinct(sec031,`sec031_var008_Past History`))
(distinct(sec031,`sec031_var009_Family History`))
(distinct(sec032,`sec032_var001_Height in Cms`))
(distinct(sec032,`sec032_var002_Weight in Kgs`))
(distinct(sec032,`sec032_var003_BP`))
(distinct(sec032,`sec032_var004_Pulse`))
(distinct(sec032,`sec032_var005_Built`))
(distinct(sec032,`sec032_var006_Temperature`))
(distinct(sec033,`sec033_var001_OD`))
(distinct(sec033,`sec033_var002_OS`))
(distinct(sec033,`sec033_var003_OD`))
(distinct(sec033,`sec033_var004_OS`))
(distinct(sec033,`sec033_var005_OD`))
(distinct(sec033,`sec033_var006_OS`))
(distinct(sec033,`sec033_var007_OD`))
(distinct(sec033,`sec033_var008_OS`))
(distinct(sec034,`sec034_var001_Right`))
(distinct(sec034,`sec034_var002_Left`))
(distinct(sec034,`sec034_var003_Right`))
(distinct(sec034,`sec034_var004_Left`))
(distinct(sec034,`sec034_var005_Right`))
(distinct(sec034,`sec034_var006_Left`))
(distinct(sec034,`sec034_var007_Right`))
(distinct(sec034,`sec034_var008_Left`))
(distinct(sec035,`sec035_var001_Retinoscopy`))
(distinct(sec035,`sec035_var002_Acceptance`))
(distinct(sec035,`sec035_var003_ST(SCHIOTZ TONOMETRY) OD`))
(distinct(sec035,`sec035_var004_Findings`))
(distinct(sec035,`sec035_var005_Final Diagnosis`))
(distinct(sec035,`sec035_var006_Doctor's Signature`))
(distinct(sec036,`sec036_var001_Main Complaints`))
(distinct(sec036,`sec036_var002_Associated Symptoms`))
(distinct(sec036,`sec036_var003_History Of Present Illness`))
(distinct(sec036,`sec036_var004_History of Past illness (Upadrava)`))
(distinct(sec036,`sec036_var005_Family History`))
(distinct(sec037,`sec037_var001_Potatoes`))
(distinct(sec037,`sec037_var002_Tomatoes`))
(distinct(sec037,`sec037_var003_Spinach`))
(distinct(sec037,`sec037_var004_Rice`))
(distinct(sec037,`sec037_var005_Wheat`))
(distinct(sec037,`sec037_var006_Ragi`))
(distinct(sec037,`sec037_var007_Green Gram`))
(distinct(sec037,`sec037_var008_Black Gram`))
(distinct(sec037,`sec037_var009_Chanaka Gram`))
(distinct(sec037,`sec037_var010_Aprouted`))
(distinct(sec037,`sec037_var011_FastFoods`))
(distinct(sec037,`sec037_var012_Chats`))
(distinct(sec037,`sec037_var013_Pizza`))
(distinct(sec037,`sec037_var014_Biscuits`))
(distinct(sec037,`sec037_var015_Cake/Pasteries`))
(distinct(sec037,`sec037_var016_Sweets`))
(distinct(sec037,`sec037_var017_Milk`))
(distinct(sec037,`sec037_var018_Curds`))
(distinct(sec037,`sec037_var019_Ghee`))
(distinct(sec037,`sec037_var020_Paneer`))
(distinct(sec037,`sec037_var021_Soft drinks`))
(distinct(sec037,`sec037_var022_Hot Drinks`))
(distinct(sec037,`sec037_var023_Milk Shakes`))
(distinct(sec037,`sec037_var024_Pickles`))
(distinct(sec037,`sec037_var025_Chutneys`))
(distinct(sec037,`sec037_var026_Chillies`))
(distinct(sec037,`sec037_var027_Garlic`))
(distinct(sec037,`sec037_var028_Ginger`))
(distinct(sec037,`sec037_var029_Refined Oil`))
(distinct(sec037,`sec037_var030_Non Refined Oil`))
(distinct(sec037,`sec037_var031_Cucumber`))
(distinct(sec037,`sec037_var032_Fruit Salads`))
(distinct(sec037,`sec037_var033_Carrot`))
(distinct(sec037,`sec037_var034_Onion`))
(distinct(sec037,`sec037_var035_Raddish`))
(distinct(sec037,`sec037_var036_Stale food intake frequency`))
(distinct(sec037,`sec037_var037_Water Intake frequency`))
(distinct(sec037,`sec037_var038_Totla Quantity in Lts`))
(distinct(sec037,`sec037_var039_Fasting Frequency`))
(distinct(sec038,`sec038_var001_Breakfast`))
(distinct(sec038,`sec038_var002_Lunch`))
(distinct(sec038,`sec038_var003_Dinner`))
(distinct(sec038,`sec038_var004_Timing Of work`))
(distinct(sec038,`sec038_var005_Nature Of Work`))
(distinct(sec038,`sec038_var006_Wake UpTime`))
(distinct(sec038,`sec038_var007_Sleeping Time`))
(distinct(sec038,`sec038_var008_Smell`))
(distinct(sec038,`sec038_var009_Consistency(Well formed/hard/Liquid)`))
(distinct(sec038,`sec038_var010_Frequency`))
(distinct(sec038,`sec038_var011_Colour`))
(distinct(sec038,`sec038_var012_Smell`))
(distinct(sec038,`sec038_var013_Any Complaints`))
(distinct(sec038,`sec038_var014_Alcohol`))
(distinct(sec038,`sec038_var015_Pan`))
(distinct(sec038,`sec038_var016_Others`))
(distinct(sec038,`sec038_var017_Cycle`))
(distinct(sec038,`sec038_var018_Psychological`))
(distinct(sec038,`sec038_var019_Appearance`))
(distinct(sec038,`sec038_var020_Body Weight`))
(distinct(sec038,`sec038_var021_Pulse (Nadi)`))
(distinct(sec038,`sec038_var022_Blood Pressure`))
(distinct(sec038,`sec038_var023_Appearance`))
(distinct(sec038,`sec038_var024_Body weight in kgs`))
(distinct(sec038,`sec038_var025_Pulse (Nadi)`))
(distinct(sec038,`sec038_var026_Blood Pressure`))
(distinct(sec044,`sec044_var001_Notes`))
(distinct(sec077,`sec077_var001_Chief Complaint with Onset & Duration`))
(distinct(sec077,`sec077_var002_Upashaya`))
(distinct(sec077,`sec077_var003_Anupashaya`))
(distinct(sec077,`sec077_var004_Associated Complaint with Onset & Duration`))
(distinct(sec077,`sec077_var005_Diabetes`))
(distinct(sec077,`sec077_var006_Hypertension`))
(distinct(sec077,`sec077_var007_Allergy`))
(distinct(sec077,`sec077_var008_Renal Diseases`))
(distinct(sec077,`sec077_var009_Liver Diseases`))
(distinct(sec077,`sec077_var010_Food Allergy`))
(distinct(sec077,`sec077_var011_Food Intolerance`))
(distinct(sec078,`sec078_var001_Menarche (yrs)`))
(distinct(sec078,`sec078_var002_Menopause (yrs)`))
(distinct(sec078,`sec078_var003_MH`))
(distinct(sec078,`sec078_var004_LMP`))
(distinct(sec078,`sec078_var005_PMH`))
(distinct(sec078,`sec078_var006_Colour`))
(distinct(sec078,`sec078_var007_Consistency`))
(distinct(sec078,`sec078_var008_Characteristics`))
(distinct(sec078,`sec078_var009_Flow`))
(distinct(sec078,`sec078_var010_Clots`))
(distinct(sec078,`sec078_var011_Smell`))
(distinct(sec078,`sec078_var012_Discharge`))
(distinct(sec078,`sec078_var013_Pre Menstrual Symptoms`))
(distinct(sec078,`sec078_var014_Menopausal Symptoms`))
(distinct(sec079,`sec079_var001_Dooshya`))
(distinct(sec079,`sec079_var002_Mala`))
(distinct(sec079,`sec079_var003_Mutra`))
(distinct(sec079,`sec079_var004_Srotas`))
(distinct(sec079,`sec079_var005_Ati pravrutti`))
(distinct(sec080,`sec080_var001_Nidana`))
(distinct(sec080,`sec080_var002_Poorvaroopa`))
(distinct(sec080,`sec080_var003_Roopa`))
(distinct(sec080,`sec080_var004_Upashaya/Anupashaya`))
(distinct(sec081,`sec081_var001_Screening Doctor`))
(distinct(sec081,`sec081_var002_Session End Time`))
(distinct(sec081,`sec081_var003_Session Start Time`))
(distinct(sec082,`sec082_var001_Allopathic Diagnosis`))
(distinct(sec083,`sec083_var001_Examination`))
(distinct(sec083,`sec083_var002_Neurological`))
(distinct(sec083,`sec083_var003_Ophthalmic`))
(distinct(sec083,`sec083_var004_ENT`))
(distinct(sec083,`sec083_var005_Cardiovascular`))
(distinct(sec083,`sec083_var006_Respiratory`))
(distinct(sec083,`sec083_var007_Gastrointestinal`))
(distinct(sec083,`sec083_var008_Urinary`))
(distinct(sec083,`sec083_var009_Genital`))
(distinct(sec083,`sec083_var010_Musculoskeletal`))
(distinct(sec083,`sec083_var011_Integumentary`))
(distinct(sec083,`sec083_var012_Endocrine`))
(distinct(sec083,`sec083_var013_Psychiatric`))
(distinct(sec083,`sec083_var014_Hemotological/Lymphatic`))
(distinct(sec083,`sec083_var015_Allergic/Immunologic`))
(distinct(sec084,`sec084_var001_Investigation Reports`))
(distinct(sec085,`sec085_var001_Complaint`))
(distinct(sec085,`sec085_var002_Doctor's Notes`))
(distinct(sec085,`sec085_var003_Source of History`))
(distinct(sec086,`sec086_var001_Examination`))
(distinct(sec088,`sec088_var001_Yes`))
(distinct(sec088,`sec088_var002_Yes`))
(distinct(sec088,`sec088_var003_No`))
(distinct(sec088,`sec088_var004_Yes`))
(distinct(sec088,`sec088_var005_Yes`))
(distinct(sec088,`sec088_var006_No`))
(distinct(sec088,`sec088_var007_General Dietic restrictions`))
(distinct(sec088,`sec088_var008_Yes`))
(distinct(sec088,`sec088_var009_Consultant Dietic Restrictions`))
(distinct(sec088,`sec088_var010_Normal`))
(distinct(sec088,`sec088_var011_<50 %`))
(distinct(sec088,`sec088_var012_Yes`))
(distinct(sec088,`sec088_var013_Junk Foods`))
(distinct(sec088,`sec088_var014_Untimely Food`))
(distinct(sec088,`sec088_var015_Excessive Food`))
(distinct(sec089,`sec089_var001_Appearance`))
(distinct(sec089,`sec089_var002_Pallor`))
(distinct(sec089,`sec089_var003_Icterus`))
(distinct(sec089,`sec089_var004_Odema`))
(distinct(sec089,`sec089_var005_Lymphadenopathy`))
(distinct(sec089,`sec089_var006_Nourishment`))
(distinct(sec089,`sec089_var007_Posture`))
(distinct(sec089,`sec089_var008_Mental State`))
(distinct(sec089,`sec089_var009_Facies`))
(distinct(sec089,`sec089_var010_Appearance`))
(distinct(sec089,`sec089_var011_Body Built`))
(distinct(sec089,`sec089_var012_Body Strength`))
(distinct(sec089,`sec089_var013_Orientation`))
(distinct(sec089,`sec089_var014_Conciousness`))
(distinct(sec099,`sec099_var001_Doctor Advice`))
(distinct(sec100,`sec100_var001_DANTA MOOLA`))
(distinct(sec100,`sec100_var002_DANTA`))
(distinct(sec100,`sec100_var003_JIHVA`))
(distinct(sec100,`sec100_var004_EXAMINATIONATION`))
(distinct(sec100,`sec100_var005_Talu`))
(distinct(sec100,`sec100_var006_GALA`))
(distinct(sec100,`sec100_var007_INVESTIGATIONS`))
(distinct(sec101,`sec101_var001_EAM`))
(distinct(sec101,`sec101_var002_TM`))
(distinct(sec101,`sec101_var003_EXAMINATIONS`))
(distinct(sec102,`sec102_var001_External Nose`))
(distinct(sec102,`sec102_var002_Septum`))
(distinct(sec102,`sec102_var003_Nasal Cavity`))
(distinct(sec102,`sec102_var004_Investigations`))
(distinct(sec103,`sec103_var001_Pain`))
(distinct(sec103,`sec103_var002_HTN`))
(distinct(sec103,`sec103_var003_Any others`))
(distinct(sec106,`sec106_var001_Additional Data`))
(distinct(sec111,`sec111_var001_Nadi`))
(distinct(sec111,`sec111_var002_Jihwa`))
(distinct(sec111,`sec111_var003_Mala`))
(distinct(sec111,`sec111_var004_Mutra`))
(distinct(sec111,`sec111_var005_Shabda`))
(distinct(sec111,`sec111_var006_Sparsha`))
(distinct(sec111,`sec111_var007_Drik`))
(distinct(sec111,`sec111_var008_Akruthi`))
(distinct(sec112,`sec112_var001_Prakriti`))
(distinct(sec112,`sec112_var002_Sara`))
(distinct(sec112,`sec112_var003_Samhanana`))
(distinct(sec112,`sec112_var004_Pramana`))
(distinct(sec112,`sec112_var005_Ahara shakti`))
(distinct(sec112,`sec112_var006_Vyayama Shakti`))
(distinct(sec112,`sec112_var007_Satmya`))
(distinct(sec112,`sec112_var008_Satwa`))
(distinct(sec112,`sec112_var009_Vaya`))
(distinct(sec114,`sec114_var001_Treatment procedures`))
(distinct(sec115,`sec115_var001_Final Diagnosis`))
(distinct(sec116,`sec116_var001_Physiotherapy Treatment Plan`))
(distinct(sec119,`sec119_var001_`))
(distinct(sec120,`sec120_var001_Assesment`))
(distinct(sec122,`sec122_var001_Allopathic Diagnosis`))
(distinct(sec123,`sec123_var001_Allopathic Diagnosis`))
(distinct(sec124,`sec124_var001_Chief Complaints`))
(distinct(sec124,`sec124_var002_History & presenting illness`))
(distinct(sec126,`sec126_var001_Stains`))
(distinct(sec126,`sec126_var002_Calculus`))
(distinct(sec126,`sec126_var003_Attrition`))
(distinct(sec126,`sec126_var004_Abrasion`))
(distinct(sec126,`sec126_var005_Grade I`))
(distinct(sec126,`sec126_var006_Grade II`))
(distinct(sec126,`sec126_var007_Grade III`))
(distinct(sec126,`sec126_var008_Class I`))
(distinct(sec126,`sec126_var009_Present`))
(distinct(sec126,`sec126_var010_Present`))
(distinct(sec126,`sec126_var011_Present`))
(distinct(sec126,`sec126_var012_Absent`))
(distinct(sec126,`sec126_var013_Attached Gingiva`))
(distinct(sec126,`sec126_var014_Mucosal Lesion`))
(distinct(sec126,`sec126_var015_Ulcer`))
(distinct(sec126,`sec126_var016_Swelling`))
(distinct(sec126,`sec126_var017_Others`))
(distinct(sec126,`sec126_var018_Provisional Diagnosis`))
(distinct(sec126,`sec126_var019_Differential Diagnosis`))
(distinct(sec126,`sec126_var020_IOPAR`))
(distinct(sec126,`sec126_var021_OPG`))
(distinct(sec126,`sec126_var022_Others`))
(distinct(sec126,`sec126_var023_Final Diagnosis`))
(distinct(sec126,`sec126_var024_Treatment Planned`))
(distinct(sec126,`sec126_var025_Drugs Prescribed`))
(distinct(secNA,`secNA_var001_NA`))

```
